### ISSUE TITLE
[Bug] Migrate app from ADAL to MSAL

### ISSUE THREAD

**Issue by lamaks** [microsoft/web-insights-service#290]
[Migrate applications to the Microsoft Authentication Library (MSAL)](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-migration)
[How to migrate a Node.js app from ADAL to MSAL](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-node-migration)

**Comment by pownkel** [comment]
We only use the @azure/identity sdk for AD auth, which already uses MSAL. The linked PR (#323) will remove the unused dependency on adal-node.
